ax_enum_define( sq_AL, "Albanian (Albania)" )
ax_enum_define( sq, "Albanian" )
ax_enum_define( ar_DZ, "Arabic (Algeria)" )
ax_enum_define( ar_BH, "Arabic (Bahrain)" )
ax_enum_define( ar_EG, "Arabic (Egypt)" )
ax_enum_define( ar_IQ, "Arabic (Iraq)" )
ax_enum_define( ar_JO, "Arabic (Jordan)" )
ax_enum_define( ar_KW, "Arabic (Kuwait)" )
ax_enum_define( ar_LB, "Arabic (Lebanon)" )
ax_enum_define( ar_LY, "Arabic (Libya)" )
ax_enum_define( ar_MA, "Arabic (Morocco)" )
ax_enum_define( ar_OM, "Arabic (Oman)" )
ax_enum_define( ar_QA, "Arabic (Qatar)" )
ax_enum_define( ar_SA, "Arabic (Saudi Arabia)" )
ax_enum_define( ar_SD, "Arabic (Sudan)" )
ax_enum_define( ar_SY, "Arabic (Syria)" )
ax_enum_define( ar_TN, "Arabic (Tunisia)" )
ax_enum_define( ar_AE, "Arabic (United Arab Emirates)" )
ax_enum_define( ar_YE, "Arabic (Yemen)" )
ax_enum_define( ar, "Arabic" )
ax_enum_define( be_BY, "Belarusian (Belarus)" )
ax_enum_define( be, "Belarusian" )
ax_enum_define( bg_BG, "Bulgarian (Bulgaria)" )
ax_enum_define( bg, "Bulgarian" )
ax_enum_define( ca_ES, "Catalan (Spain)" )
ax_enum_define( ca, "Catalan" )
ax_enum_define( zh_CN, "Chinese (China)" )
ax_enum_define( zh_HK, "Chinese (Hong Kong)" )
ax_enum_define( zh_SG, "Chinese (Singapore)" )
ax_enum_define( zh_TW, "Chinese (Taiwan)" )
ax_enum_define( zh, "Chinese" )
ax_enum_define( hr_HR, "Croatian (Croatia)" )
ax_enum_define( hr, "Croatian" )
ax_enum_define( cs_CZ, "Czech (Czech Republic)" )
ax_enum_define( cs, "Czech" )
ax_enum_define( da_DK, "Danish (Denmark)" )
ax_enum_define( da, "Danish" )
ax_enum_define( nl_BE, "Dutch (Belgium)" )
ax_enum_define( nl_NL, "Dutch (Netherlands) " )
ax_enum_define( nl, "Dutch" )
ax_enum_define( en_AU, "English (Australia)" )
ax_enum_define( en_CA, "English (Canada)" )
ax_enum_define( en_IN, "English (India)" )
ax_enum_define( en_IE, "English (Ireland)" )
ax_enum_define( en_MT, "English (Malta)" )
ax_enum_define( en_NZ, "English (New Zealand)" )
ax_enum_define( en_PH, "English (Philippines)" )
ax_enum_define( en_SG, "English (Singapore)" )
ax_enum_define( en_ZA, "English (South Africa)" )
ax_enum_define( en_GB, "English (United Kingdom)" )
ax_enum_define( en_US, "English (United States)" )
ax_enum_define( en, "English" )
ax_enum_define( et_EE, "Estonian (Estonia)" )
ax_enum_define( et, "Estonian" )
ax_enum_define( fi_FI, "Finnish (Finland)" )
ax_enum_define( fi, "Finnish" )
ax_enum_define( fr_BE, "French (Belgium)" )
ax_enum_define( fr_CA, "French (Canada)" )
ax_enum_define( fr_FR, "French (France)" )
ax_enum_define( fr_LU, "French (Luxembourg)" )
ax_enum_define( fr_CH, "French (Switzerland)" )
ax_enum_define( fr, "French" )
ax_enum_define( de_AT, "German (Austria)" )
ax_enum_define( de_DE, "German (Germany)" )
ax_enum_define( de_LU, "German (Luxembourg)" )
ax_enum_define( de_CH, "German (Switzerland)" )
ax_enum_define( de, "German" )
ax_enum_define( el_CY, "Greek (Cyprus)" )
ax_enum_define( el_GR, "Greek (Greece)" )
ax_enum_define( el, "Greek" )
ax_enum_define( iw_IL, "Hebrew (Israel)" )
ax_enum_define( iw, "Hebrew" )
ax_enum_define( hi_IN, "Hindi (India)" )
ax_enum_define( hu_HU, "Hungarian (Hungary)" )
ax_enum_define( hu, "Hungarian" )
ax_enum_define( is_IS, "Icelandic (Iceland)" )
ax_enum_define( is, "Icelandic" )
ax_enum_define( in_ID, "Indonesian (Indonesia)" )
ax_enum_define( in, "Indonesian" )
ax_enum_define( ga_IE, "Irish (Ireland)" )
ax_enum_define( ga, "Irish" )
ax_enum_define( it_IT, "Italian (Italy)" )
ax_enum_define( it_CH, "Italian (Switzerland)" )
ax_enum_define( it, "Italian" )
ax_enum_define( ja_JP, "Japanese (Japan)" )
ax_enum_define( ja_JP_JP, "Japanese (Japan,JP)" )
ax_enum_define( ja, "Japanese" )
ax_enum_define( ko_KR, "Korean (South Korea)" )
ax_enum_define( ko, "Korean" )
ax_enum_define( lv_LV, "Latvian (Latvia)" )
ax_enum_define( lv, "Latvian" )
ax_enum_define( lt_LT, "Lithuanian (Lithuania)" )
ax_enum_define( lt, "Lithuanian" )
ax_enum_define( mk_MK, "Macedonian (Macedonia)" )
ax_enum_define( mk, "Macedonian" )
ax_enum_define( ms_MY, "Malay (Malaysia)" )
ax_enum_define( ms, "Malay" )
ax_enum_define( mt_MT, "Maltese (Malta)" )
ax_enum_define( mt, "Maltese" )
ax_enum_define( no_NO, "Norwegian (Norway)" )
ax_enum_define( no_NO_NY, "Norwegian (Norway,Nynorsk)" )
ax_enum_define( no, "Norwegian" )
ax_enum_define( pl_PL, "Polish (Poland)" )
ax_enum_define( pl, "Polish" )
ax_enum_define( pt_BR, "Portuguese (Brazil)" )
ax_enum_define( pt_PT, "Portuguese (Portugal)" )
ax_enum_define( pt, "Portuguese" )
ax_enum_define( ro_RO, "Romanian (Romania)" )
ax_enum_define( ro, "Romanian" )
ax_enum_define( ru_RU, "Russian (Russia)" )
ax_enum_define( ru, "Russian" )
ax_enum_define( sr_BA, "Serbian (Bosnia and Herzegovina)" )
ax_enum_define( sr_ME, "Serbian (Montenegro)" )
ax_enum_define( sr_CS, "Serbian (Serbia and Montenegro)" )
ax_enum_define( sr_RS, "Serbian (Serbia)" )
ax_enum_define( sr, "Serbian" )
ax_enum_define( sk_SK, "Slovak (Slovakia)" )
ax_enum_define( sk, "Slovak" )
ax_enum_define( sl_SI, "Slovenian (Slovenia)" )
ax_enum_define( sl, "Slovenian" )
ax_enum_define( es_AR, "Spanish (Argentina)" )
ax_enum_define( es_BO, "Spanish (Bolivia)" )
ax_enum_define( es_CL, "Spanish (Chile)" )
ax_enum_define( es_CO, "Spanish (Colombia)" )
ax_enum_define( es_CR, "Spanish (Costa Rica)" )
ax_enum_define( es_DO, "Spanish (Dominican Republic)" )
ax_enum_define( es_EC, "Spanish (Ecuador)" )
ax_enum_define( es_SV, "Spanish (El Salvador)" )
ax_enum_define( es_GT, "Spanish (Guatemala)" )
ax_enum_define( es_HN, "Spanish (Honduras)" )
ax_enum_define( es_MX, "Spanish (Mexico)	" )
ax_enum_define( es_NI, "Spanish (Nicaragua)" )
ax_enum_define( es_PA, "Spanish (Panama)" )
ax_enum_define( es_PY, "Spanish (Paraguay)" )
ax_enum_define( es_PE, "Spanish (Peru)" )
ax_enum_define( es_PR, "Spanish (Puerto Rico)" )
ax_enum_define( es_ES, "Spanish (Spain)" )
ax_enum_define( es_US, "Spanish (United States)" )
ax_enum_define( es_UY, "Spanish (Uruguay)" )
ax_enum_define( es_VE, "Spanish (Venezuela)" )
ax_enum_define( es, "Spanish" )
ax_enum_define( sv_SE, "Swedish (Sweden)" )
ax_enum_define( sv, "Swedish" )
ax_enum_define( th_TH, "Thai (Thailand)" )
ax_enum_define( th_TH_TH, "Thai (Thailand,TH)" )
ax_enum_define( th, "Thai" )
ax_enum_define( tr_TR, "Turkish (Turkey)" )
ax_enum_define( tr, "Turkish" )
ax_enum_define( uk_UA, "Ukrainian (Ukraine)" )
ax_enum_define( uk, "Ukrainian" )
ax_enum_define( vi_VN, "Vietnamese (Vietnam)" )
ax_enum_define( vi, "Vietnamese" )

