src_file_list=\
 ../../../src//database/axDBConn.cpp \
 ../../../src//database/axDBStmt.cpp \
 ../../../src//file_system/axDir.cpp \
 ../../../src//file_system/axFile.cpp \
 ../../../src//file_system/axFileStream.cpp \
 ../../../src//file_system/axFileSystem.cpp \
 ../../../src//file_system/axMemMap.cpp \
 ../../../src//math/axEulerRotation3.cpp \
 ../../../src//math/axFrustum3.cpp \
 ../../../src//math/axIntersect3.cpp \
 ../../../src//math/axMatrix4.cpp \
 ../../../src//math/axQuaternion.cpp \
 ../../../src//math/axRay3.cpp \
 ../../../src//math/axRect2.cpp \
 ../../../src//math/axVec3.cpp \
 ../../../src//math/axVec4.cpp \
 ../../../src//math/axVec_Str.cpp \
 ../../../src//net/axSockAddr.cpp \
 ../../../src//net/axSocket.cpp \
 ../../../src//other/axJson.cpp \
 ../../../src//parser/axCSVParser.cpp \
 ../../../src//parser/axIniParser.cpp \
 ../../../src//pch/pch.cpp \
 ../../../src//system/ax_poll.cpp \
 ../../../src//system/axAndroid.cpp \
 ../../../src//system/axApp.cpp \
 ../../../src//system/axCommandLineApp.cpp \
 ../../../src//system/axExecute.cpp \
 ../../../src//system/axLog.cpp \
 ../../../src//system/axSharedLibrary.cpp \
 ../../../src//system/axSystem.cpp \
 ../../../src//thread/axCondVar.cpp \
 ../../../src//thread/axMutex.cpp \
 ../../../src//thread/axThread.cpp \
 ../../../src//thread/axThreadPool.cpp  
