#ifndef __axExpandArgList_h__
#define __axExpandArgList_h__


/* !!!! 

This file generated by tools/axExpandArgList_generator.html ( java script ) 

*/


#include "ax_macro.h"



//! ==== For 0 fixed parameter ===
#define axExpandArgList0( ReturnType, FuncName, Arg, ArgList ) \
ReturnType FuncName (  );\
ReturnType FuncName ( Arg a0 );\
ReturnType FuncName ( Arg a0, Arg a1 );\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2 );\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3 );\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4 );\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5 );\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6 );\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7 );\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8 );\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9 );\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10 );\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11 );\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12 );\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13 );\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14 );\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14, Arg a15 );\
//---- End Macro ---

#define axExpandArgList0_Imp( ReturnType, FuncName, Arg, ArgList ) \
ReturnType FuncName (  ) { \
  ArgList list;\
  return axJOIN_WORD(FuncName,_ArgList)(  list ); \
};\
ReturnType FuncName ( Arg a0 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  list ); \
};\
ReturnType FuncName ( Arg a0, Arg a1 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  list ); \
};\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  list ); \
};\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  list ); \
};\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  list ); \
};\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  list ); \
};\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  list ); \
};\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  list ); \
};\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  list ); \
};\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  list ); \
};\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  list ); \
};\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  list ); \
};\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  list ); \
};\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  list ); \
};\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  st=list.addArg(a14);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  list ); \
};\
ReturnType FuncName ( Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14, Arg a15 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  st=list.addArg(a14);  if(!st) return st; \
  st=list.addArg(a15);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  list ); \
};\
//---- End Macro ---

//! ==== For 1 fixed parameter ===
#define axExpandArgList1( ReturnType, FuncName, Fixed0, Arg, ArgList ) \
ReturnType FuncName ( Fixed0 f0 );\
ReturnType FuncName ( Fixed0 f0, Arg a0 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14, Arg a15 );\
//---- End Macro ---

#define axExpandArgList1_Imp( ReturnType, FuncName, Fixed0, Arg, ArgList ) \
ReturnType FuncName ( Fixed0 f0 ) { \
  ArgList list;\
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  st=list.addArg(a14);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14, Arg a15 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  st=list.addArg(a14);  if(!st) return st; \
  st=list.addArg(a15);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
//---- End Macro ---

//! ==== For 2 fixed parameter ===
#define axExpandArgList2( ReturnType, FuncName, Fixed0, Fixed1, Arg, ArgList ) \
ReturnType FuncName ( Fixed0 f0, Fixed1 f1 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14, Arg a15 );\
//---- End Macro ---

#define axExpandArgList2_Imp( ReturnType, FuncName, Fixed0, Fixed1, Arg, ArgList ) \
ReturnType FuncName ( Fixed0 f0, Fixed1 f1 ) { \
  ArgList list;\
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  st=list.addArg(a14);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14, Arg a15 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  st=list.addArg(a14);  if(!st) return st; \
  st=list.addArg(a15);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
//---- End Macro ---

//! ==== For 3 fixed parameter ===
#define axExpandArgList3( ReturnType, FuncName, Fixed0, Fixed1, Fixed2, Arg, ArgList ) \
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14, Arg a15 );\
//---- End Macro ---

#define axExpandArgList3_Imp( ReturnType, FuncName, Fixed0, Fixed1, Fixed2, Arg, ArgList ) \
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2 ) { \
  ArgList list;\
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  st=list.addArg(a14);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14, Arg a15 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  st=list.addArg(a14);  if(!st) return st; \
  st=list.addArg(a15);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
//---- End Macro ---

//! axLog for defualt Tag
#define axLogExpandArgListStdTag1( ReturnType, FuncName, Fixed0, Arg, ArgList ) \
ReturnType FuncName ( Fixed0 f0 );\
ReturnType FuncName ( Fixed0 f0, Arg a0 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14 );\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14, Arg a15 );\
//---- End Macro ---

#define axLogExpandArgListStdTag1_Imp( ReturnType, FuncName, Fixed0, Arg, ArgList ) \
ReturnType FuncName ( Fixed0 f0 ) { \
  ArgList list;\
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  st=list.addArg(a14);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14, Arg a15 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  st=list.addArg(a14);  if(!st) return st; \
  st=list.addArg(a15);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, list ); \
};\
//---- End Macro ---

//! axLog for defualt Tag
#define axLogExpandArgListStdTag2( ReturnType, FuncName, Fixed0, Fixed1, Arg, ArgList ) \
ReturnType FuncName ( Fixed0 f0, Fixed1 f1 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14, Arg a15 );\
//---- End Macro ---

#define axLogExpandArgListStdTag2_Imp( ReturnType, FuncName, Fixed0, Fixed1, Arg, ArgList ) \
ReturnType FuncName ( Fixed0 f0, Fixed1 f1 ) { \
  ArgList list;\
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  st=list.addArg(a14);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14, Arg a15 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  st=list.addArg(a14);  if(!st) return st; \
  st=list.addArg(a15);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
//---- End Macro ---

//! axLog for user Tag
#define axLogExpandArgListUserTag2( ReturnType, FuncName, Fixed0, Fixed1, Arg, ArgList ) \
ReturnType FuncName ( Fixed0 f0, Fixed1 f1 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14, Arg a15 );\
//---- End Macro ---

#define axLogExpandArgListUserTag2_Imp( ReturnType, FuncName, Fixed0, Fixed1, Arg, ArgList ) \
ReturnType FuncName ( Fixed0 f0, Fixed1 f1 ) { \
  ArgList list;\
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  st=list.addArg(a14);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14, Arg a15 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  st=list.addArg(a14);  if(!st) return st; \
  st=list.addArg(a15);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, list ); \
};\
//---- End Macro ---

//! axLog for user Tag
#define axLogExpandArgListUserTag3( ReturnType, FuncName, Fixed0, Fixed1, Fixed2, Arg, ArgList ) \
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14 );\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14, Arg a15 );\
//---- End Macro ---

#define axLogExpandArgListUserTag3_Imp( ReturnType, FuncName, Fixed0, Fixed1, Fixed2, Arg, ArgList ) \
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2 ) { \
  ArgList list;\
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  st=list.addArg(a14);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
ReturnType FuncName ( Fixed0 f0, Fixed1 f1, Fixed2 f2, Arg a0, Arg a1, Arg a2, Arg a3, Arg a4, Arg a5, Arg a6, Arg a7, Arg a8, Arg a9, Arg a10, Arg a11, Arg a12, Arg a13, Arg a14, Arg a15 ) { \
  ArgList list;\
  axStatus st;\
  st=list.addArg(a0);  if(!st) return st; \
  st=list.addArg(a1);  if(!st) return st; \
  st=list.addArg(a2);  if(!st) return st; \
  st=list.addArg(a3);  if(!st) return st; \
  st=list.addArg(a4);  if(!st) return st; \
  st=list.addArg(a5);  if(!st) return st; \
  st=list.addArg(a6);  if(!st) return st; \
  st=list.addArg(a7);  if(!st) return st; \
  st=list.addArg(a8);  if(!st) return st; \
  st=list.addArg(a9);  if(!st) return st; \
  st=list.addArg(a10);  if(!st) return st; \
  st=list.addArg(a11);  if(!st) return st; \
  st=list.addArg(a12);  if(!st) return st; \
  st=list.addArg(a13);  if(!st) return st; \
  st=list.addArg(a14);  if(!st) return st; \
  st=list.addArg(a15);  if(!st) return st; \
  return axJOIN_WORD(FuncName,_ArgList)(  f0, f1, f2, list ); \
};\
//---- End Macro ---



#endif //__axExpandArgList_h__
